#!/bin/bash
# Quick Reference - TrailHub Frontend Testing

echo "=========================================="
echo "  TrailHub Frontend Testing - Quick Help  "
echo "=========================================="
echo ""
echo "UNIT TESTS (Vitest)"
echo "  npm run test              - Watch mode (auto-reload)"
echo "  npm run test:run          - Run once (CI mode)"
echo "  npm run test:ui           - Interactive UI dashboard"
echo "  npm run test:coverage     - With coverage report"
echo ""
echo "E2E TESTS (Playwright)"
echo "  npm run e2e               - Run all tests"
echo "  npm run e2e:ui            - Interactive mode"
echo "  npm run e2e:debug         - Debug (browser visible)"
echo ""
echo "STATUS:"
echo "  ✅ Unit Tests:   11/11 passing"
echo "  ✅ E2E Tests:    Ready (run with 'npm run e2e')"
echo ""
echo "FILES:"
echo "  src/__tests__/       - Unit test files"
echo "  e2e/                 - E2E test files"
echo "  vitest.config.js     - Unit test config"
echo "  playwright.config.js - E2E test config"
echo ""
echo "COMMON ISSUES:"
echo "  • E2E tests require backend running (npm run dev)"
echo "  • Unit tests run standalone"
echo "  • Use --reporter=verbose for detailed output"
echo ""
