#!/bin/bash
# Quick Test Runner - TrailHub Frontend

echo "🧪 TrailHub Frontend Testing"
echo "============================"
echo ""
echo "Prerequisites:"
echo "  • Backend running: npm run dev (root)"
echo "  • Frontend dev server: npm run dev (frontend/)"
echo ""
echo "Available Commands:"
echo ""
echo "Unit Tests (Vitest):"
echo "  npm run test              - Run tests in watch mode"
echo "  npm run test:ui           - Interactive test dashboard"
echo "  npm run test:run          - Run once (CI mode)"
echo "  npm run test:coverage     - Generate coverage report"
echo ""
echo "E2E Tests (Playwright):"
echo "  npm run e2e               - Run all tests"
echo "  npm run e2e:ui            - Interactive test UI"
echo "  npm run e2e:debug         - Debug mode (browser visible)"
echo ""
echo "Quick Setup (if not done yet):"
echo "  cd frontend"
echo "  npm install"
echo "  npm run test              # Start unit tests"
echo ""
echo "Next: Run one of the commands above!"
